getMatch works
bavaz1/go-pubg pull request #1
Opened 2018-12-09 21:36 UTC by bavaz1

2018-12-10 10:29 UTC, PumpkinSeed requested changes
Write a request method, and it will do the actual request, waits parameters like `method, url, etc.` and returns a []byte of the response and error.

2018-12-10 10:29 UTC, PumpkinSeed commented on sdk/sdk.go
>  	s := []string{apiHost, apiEndpoint, apiShard, apiFilter}
Use strings.Builder

2018-12-10 10:29 UTC, PumpkinSeed commented on sdk/sdk.go
> +func GetPlayer(ctx context.Context, playerName string, client *http.Client) (Players, error) {
Use pointer for Players, you can use nil in returns

2018-12-10 10:29 UTC, PumpkinSeed commented on sdk/sdk.go
> +		return Players{}, err
return nil, err

2018-12-10 10:29 UTC, PumpkinSeed commented on sdk/sdk.go
> +		return Players{}, err
return nil, err

2018-12-10 10:29 UTC, PumpkinSeed commented on sdk/sdk.go
> +		return Players{}, err
return nil, err

2018-12-10 10:29 UTC, PumpkinSeed commented on sdk/sdk.go
> +	return Players{}, fmt.Errorf("Undefined status code: %s", string(body))
return nil, ....

2018-12-10 10:29 UTC, PumpkinSeed commented on sdk/sdk.go
>  	s := []string{apiHost, apiEndpoint, apiShard, apiMatches, matchID}
Use strings.Builder

2018-12-10 10:29 UTC, PumpkinSeed commented on sdk/sdk.go
> +func GetMatch(ctx context.Context, matchID string, client *http.Client) (Match, error) {
return Match as pointer

2018-12-10 10:29 UTC, PumpkinSeed commented on sdk/sdk.go
> +		return Match{}, err
return nil, err

2018-12-10 10:29 UTC, PumpkinSeed commented on sdk/sdk.go
> +		return Match{}, err
return nil, err

2018-12-10 10:29 UTC, PumpkinSeed commented on sdk/sdk.go
> +		return Match{}, err
return nil, err

2018-12-10 10:29 UTC, PumpkinSeed commented on sdk/sdk.go
> +	return Match{}, fmt.Errorf("Undefined status code: %s", string(body))
return nil, ...

2018-12-11 01:44 UTC, bavaz1 commented
Request function is added, but i dont get it why should i use strings.Builder. Could you explain that please?

2018-12-11 09:16 UTC, PumpkinSeed approved these changes

2018-12-11 09:16 UTC, merged